### ISSUE TITLE
Builds are not reproducible (due to bug in coreLibraryDesugaring)

### ISSUE THREAD

**Issue by relan** [iNPUTmice/lttrs-android#99] opened 2021-06-22 10:05 UTC
I was trying to understand why F-Droid's build of 0.1.4 is different from the one supplied in https://ltt.rs/fdroid/repo and found that the APK in your repo does not correspond to the source code under the 0.1.4 tag. For example, [0.1.4 must have minSdk 26](https://github.com/iNPUTmice/lttrs-android/blob/0.1.4/app/build.gradle#L10), but the APK doesn't:

    $ wget --quiet https://ltt.rs/fdroid/repo/Ltt.rs-0.1.4-release.apk
    $ aapt dump badging Ltt.rs-0.1.4-release.apk | head -n3
    package: name='rs.ltt.android' versionCode='5' versionName='0.1.4' compileSdkVersion='30' compileSdkVersionCodename='11'
    sdkVersion:'23'
    targetSdkVersion:'30'

Could you check that please?

**Comment by iNPUTmice** [comment] 2021-06-22 10:46
Builds are currently not reproducible.

The introduction of `coreLibraryDesugaring` (I think) broke it. What you currently see in the repo are relics from trying to figure out what went wrong and why builds are no longer reproducible. (minSdk=26 has native Java 8 and doesn’t require de-sugaring.)

I’m currently more than busy developing actual features for the app and making it reproducible has absolutely no priority right now.

You are very welcome to figure this out and provide a PR.

**Comment by relan** [comment] 2021-06-23 08:36
> Builds are currently not reproducible.
> The introduction of coreLibraryDesugaring (I think) broke it.

I don't think desugaring breaks reproducibility. As an experiment, I built 0.1.4 APKs on two machines in different environments and got identical binaries.

> What you currently see in the repo are relics from trying to figure out what went wrong and why builds are no longer reproducible.

OK. It looked suspicious to me that 0.1.4 APK in your repo does not correspond the source code. Thanks for clearing this.

Anyway, F-Droid can't handle reproducible builds with v2/v3 signatures right now: https://gitlab.com/fdroid/fdroidserver/-/issues/797. So I'm closing this.

**Comment by iNPUTmice** [comment] 2021-06-23 13:03
> I don't think desugaring breaks reproducibility. 

It shouldn’t. I'm seeing other reproducible projects using it just fine. NewPipe for instance. However it my tests the builds suddenly broke around the same time I introduced core library desugaring (not regular desugaring)

Anyway I'll probably tag a 0.2.0-alpha soonish and we can try this again.

**Comment by licaon-kter** [comment] 2021-06-23 15:19
See https://github.com/TeamNewPipe/NewPipe/issues/6486 :(

**Comment by iNPUTmice** [comment] 2021-06-23 15:26
Huh that issue didn’t exist last time I checked. Thanks for digging that up @licaon-kter

**Comment by obfusk** [comment] 2021-06-24 17:25
> Anyway, F-Droid can't handle reproducible builds with v2/v3 signatures right now: https://gitlab.com/fdroid/fdroidserver/-/issues/797.

v2/v3 signatures work just fine since https://gitlab.com/fdroid/fdroidserver/-/merge_requests/893 was merged :)

**Comment by linsui** [comment] 2021-08-09 07:16
The apk of 0.2.0 has not published to you repo.

**Closed** 2021-08-18 11:43 UTC
Labels: bug, help wanted

**Comment by linsui** [comment] 2021-08-18 11:56
'https://storage.googleapis.com/r8-releases/raw' is not allowed in F-Droid. We can only use r8 from `google()`.

**Comment by licaon-kter** [comment] 2021-08-18 13:57
The thing is that sometimes non-release versions of stuff (eg. Gradle) are not FOSS. Each maven repo that we allow has a policy of hosting only FOSS stuff, that maven is managed how?

**Comment by obfusk** [comment] 2021-08-19 09:50
The fix seems to be in older, published versions of R8 as well. This patch seems to work for NewPipe:

```diff
diff --git a/build.gradle b/build.gradle
index 315625a0f..9548d1080 100644
--- a/build.gradle
+++ b/build.gradle
@@ -7,6 +7,7 @@ buildscript {
         google()
     }
     dependencies {
+        classpath 'com.android.tools:r8:2.2.64' // must be before com.android.tools.build:gradle
         classpath 'com.android.tools.build:gradle:4.1.3'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

```
